name: TODO - remove this workflow after testing
on:
  workflow_dispatch:

jobs:
  sleep:
    name: Sleep for a while
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for 5 minutes
      run: sleep 300