name: Workflow to check for long running workflows
on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/30 * * * *'

jobs:
  check-running-jobs:
    name: Job to check for long running jobs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Call workflow cleaner
      uses: ./
      with:
        app-id: ${{secrets.GHA_WORKFLOWS_CLEANER_APP_ID}}
        app-pk: ${{secrets.GHA_WORKFLOWS_CLEANER_PRIVATE_KEY}}
        timeout-minutes: 1