name: Scheduled workflow to check for long running workflows
on:
  workflow_dispatch:

jobs:
  check-running-jobs:
    name: Job to check for long running jobs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Call workflow cleaner
      uses: ./.github/actions/workflow-cleaner
      with:
        app-id: ${{secrets.GHA_WORKFLOWS_CLEANER_APP_ID}}
        app-pk: ${{secrets.GHA_WORKFLOWS_CLEANER_PRIVATE_KEY}}