name: Workflow to check for long running workflows
on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/30 * * * *'

jobs:
  check-running-jobs:
    name: Job to check for long running jobs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Call workflow cleaner
      uses: BrainsDevOps/timeouts-action@feature/more-unit-tests
      id: cleaner
      with:
        app-id: ${{secrets.GHA_WORKFLOWS_CLEANER_APP_ID}}
        app-pk: ${{secrets.GHA_WORKFLOWS_CLEANER_PRIVATE_KEY}}
        timeout-minutes: 1

    - name: Summary
      run: |
        echo "# Workflow cleaner summary" >> $GITHUB_STEP_SUMMARY
        echo "${{steps.cleaner.outputs.report}}" >> $GITHUB_STEP_SUMMARY
